# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stefano Travasci
email: stefanotravasci@gmail.com
description: "The personal site of Stefano Travasci"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stefanotravasci.it" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  StefanoTrv
timezone: Europe/Rome
#og_image: TODO

author:
  name : Stefano Travasci
  email: stefanotravasci@gmail.com
  uri: "https://stefanotravasci.it"
  avatar : /assets/img/profile.jpg
  location : Pordenone, Italy
  links:
    - url   : https://github.com/StefanoTrv
      icon  : "fa-brands fa-github"
      label : "My Github profile"
    - url   : https://www.linkedin.com/in/stefano-travasci/
      icon  : "fa-brands fa-linkedin"
      label : "My LinkedIn profile"
    - url   : https://orcid.org/0000-0001-5693-6033
      icon  : "fa-brands fa-orcid"
      label : "My ORCID profile"
    - url   : https://www.researchgate.net/profile/Stefano-Travasci
      icon  : "fa-brands fa-researchgate"
      label : "My ResearchGate profile"

# Build settings
theme: chulapa-jekyll
chulapa-skin:
  highlight     :  stackoverflow.light # default["default"]
  skin          :   navi # Optional predefined skins
  autothemer    :  true # Bool: Use autotheming
  vars          :
    primary     : #default ["#007bff"] - Bootstrap blue

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search: false
      #cloudtag_url        : /tags #This is where the link on tags would redirect
      #cloudcategory_url   : /categories #This is where the link on categories would redirect
  -
    scope:
      type: "posts"
    values:
      permalink: /:year/:month/:day/:title
      layout: "default"
      header_type       : "post"
      #include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_bottomnavs   : true
      show_sociallinks  : true
      #show_comments     : true
      #show_tags         : true
      #show_categories   : true
      show_author       : true
      #show_breadcrumb   : true
      #breadcrumb_list   :
      #  - label: Blog
      #    url: /blog/

navbar:
  style :  fab 
  brand:
    title :  Home
    img: "./assets/img/green_pizza.png"
    url: /
  nav:
  - title: One-level link #Label
    url: /url1/  #url
  - title: Two-level link #Label
    child:
    - title: Second level first item
      url: /url2-1
    - title: Second level second item
      url: /url2-2
  - title: One-level link #Label
    url: /url1/  #url

footer:
  links:
    #- label: "RSS"
    #  icon: "fa fa-rss"
    #  url:  "./feed.xml"
    - url   : https://github.com/StefanoTrv
      icon  : "fa-brands fa-github"
      label : "My Github profile"
    - url   : https://www.linkedin.com/in/stefano-travasci/
      icon  : "fa-brands fa-linkedin"
      label : "My LinkedIn profile"
    - url   : https://orcid.org/0000-0001-5693-6033
      icon  : "fa-brands fa-orcid"
      label : "My ORCID profile"
    - url   : https://www.researchgate.net/profile/Stefano-Travasci
      icon  : "fa-brands fa-researchgate"
      label : "My ResearchGate profile"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - mixed-decls
    - abs-percent
    - function-units
    - color-functions

